name: Upload to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - web/static/**

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.PUBLIC_BUCKET_CREATOR }}

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'web/static/events-ai-loading.html'
          destination: 'events-ai-public'
